//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DesktopApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class Task
    {
        public int TaskId { get; set; }
        public string TypeOfService { get; set; }
        public string Status { get; set; }
        public System.DateTime TimeIssued { get; set; }
        public Nullable<System.DateTime> TimeCompleted { get; set; }
        public int RoomId { get; set; }
        public string Description { get; set; }
    
        public virtual Room Room { get; set; }
    }
}
